--- 
addons:
   snaps:
     - minizinc --classic

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      wget https://github.com/MiniZinc/MiniZincIDE/releases/download/2.4.3/MiniZincIDE-2.4.3-bundled.dmg ;
      sudo hdiutil attach MiniZincIDE-2.4.3-bundled.dmg ;
      sudo installer -package '''/Volumes/MiniZinc IDE 2.4.3 (bundled)/MiniZincIDE.app -target / ''' ;
      sudo hdiutil detach ''' /Volumes/MiniZinc IDE 2.4.3 (bundled) ''' ;
    fi

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export PATH=/Applications/MiniZincIDE.app/Contents/Resources:$PATH ;
    fi

cache: packages
language: R
os: 
  - linux
  - osx
