--- 
warnings_are_errors: false
jobs:
  include:
    - os: linux
      language: R
      sudo: required
      before_install:
        - ls;
        - ls /home/travis/build/acharaakshit;
        - ls /home/travis/build/acharaakshit/RMiniZinc;
        - ls /home/travis/build/acharaakshit/RMiniZinc/src;
        - cd /usr/local/lib;
        - sudo git clone https://github.com/MiniZinc/libminizinc.git; 
        - cd libminizinc/;
        - sudo sed -i '3 i set(CMAKE_POSITION_INDEPENDENT_CODE ON)' CMakeLists.txt;
        - sudo apt-get install build-essential cmake;
        - sudo -E cmake CMakeLists.txt;
        - sudo make;
        - sudo make install;
        - sudo cp -r /snap/minizinc/current/share/minizinc/solvers  /usr/local/lib/libminizinc/share/minizinc;
        - cd share/minizinc/solvers;
        - sudo sed -i 's+../../../bin+/snap/minizinc/current/bin+g' gecode.msc; 
        - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/libminizinc;
        - sudo echo 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/libminizinc' >> ~/.bashrc;
        - sudo ldconfig;
        - sudo cp -r /snap/minizinc/current/share/minizinc/. /usr/local/share/minizinc/;
        - cd /usr/local/share/minizinc/solvers;
        - sudo sed -i 's+../../../bin+/snap/minizinc/current/bin+g' gecode.msc;
        - cd;
        - echo $TRAVIS_BUILD_DIR;
        - cd $TRAVIS_BUILD_DIR;
      script:
        - R CMD build .
        - R CMD INSTALL *tar.gz
        - R CMD check *tar.gz 
      addons:
        snaps:
          - minizinc --classic
      cache: packages
    - os: osx
      language: R
      before_install:
        - wget https://github.com/MiniZinc/MiniZincIDE/releases/download/2.4.3/MiniZincIDE-2.4.3-bundled.dmg ;
        - hdiutil mount MiniZincIDE-2.4.3-bundled.dmg ;
        - sudo cp -R '''/Volumes/MiniZinc IDE 2.4.3 (bundled)/MiniZincIDE.app''' /Applications ;
        - hdiutil unmount '''/Volumes/MiniZinc IDE 2.4.3 (bundled)/''' ;
        - export PATH=/Applications/MiniZincIDE.app/Contents/Resources:$PATH ;
        - echo PATH ;
  allow_failures:
    os: osx
   
