--- 
warnings_are_errors: false
jobs:
  include:
    - os: linux
      language: R
      sudo: required
      before_install:
        - cd /usr/local/lib;
        - sudo git clone https://github.com/MiniZinc/libminizinc.git; 
        - cd libminizinc/;
        - sudo sed -i '3 i set(CMAKE_POSITION_INDEPENDENT_CODE ON)' CMakeLists.txt;
        - sudo apt-get install build-essential cmake;
        - sudo -E cmake CMakeLists.txt;
        - sudo make;
        - sudo make install;
        - cd $TRAVIS_BUILD_DIR;
      cache: packages
    - os: osx
      language: R
      before_install:
        - cd /usr/local/lib;
        - sudo git clone https://github.com/MiniZinc/libminizinc.git; 
        - cd libminizinc/;
        - sudo sed -i '' '3i\'$'\n''set(CMAKE_POSITION_INDEPENDENT_CODE ON)' CMakeLists.txt;
        - brew install cmake;
        - sudo -E cmake CMakeLists.txt;
        - sudo make;
        - sudo make install;
        - cd $TRAVIS_BUILD_DIR;
   
