# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title MiniZinc model evaluation
#' 
#' @description evaluates the MiniZinc model
#'
#' @importFrom Rcpp sourceCpp
#' @export mzn_eval
#' @useDynLib rminizinc, .registration=TRUE
#' @param modelString the string representation of the model to be evaluated.
#' @param solver the name of the solver to use.
#' @param libpath the path of the library where the solver is present.
#' @param mznpath the path of the MiniZinc model file.
#' @param dznpath path of the datafile to be used
mzn_eval <- function(solver, libpath, modelString = "", mznpath = "", dznpath = "") {
    .Call(`_rminizinc_mzn_eval`, solver, libpath, modelString, mznpath, dznpath)
}

#' @title MiniZinc syntax parser
#' 
#' @description parses the MiniZinc syntax into R objects
#'
#' @importFrom Rcpp sourceCpp
#' @export mzn_parse
#' @useDynLib rminizinc, .registration=TRUE
#' @param modelString string representation of the MiniZinc model.
#' @param mznpath the path of model mzn.
#' @param modelStringName the name of model string.
mzn_parse <- function(modelString = "", mznpath = "", modelStringName = "abc.mzn") {
    .Call(`_rminizinc_mzn_parse`, modelString, mznpath, modelStringName)
}

#' @title assign the missing parameters to the model
#' 
#' @desciption the missing parameters found from parse_mzn can be assigned 
#' in this function
#' 
#' @importFrom Rcpp sourceCpp
#' @export set_params
#' @useDynLib rminizinc, .registration=TRUE
#' @param modData list containing the parameter values.
#' @param modelString string representation of the MiniZinc model
#' @param mznpath path of the mzn file 
set_params <- function(modData, modelString = "", mznpath = "") {
    .Call(`_rminizinc_set_params`, modData, modelString, mznpath)
}

